### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by misialq** [bokulich-lab/q2-amr#13]
The current README is a little bit out-of-date - let's update it. Below are some things I noticed but please add anything what may still be missing:

```[tasklist]
### Tasks
- [x] the indentation in the first code block is a bit off (check https://github.com/bokulich-lab/q2-fondue to see what it should look like)
- [x] the table is missing links - maybe we could actually add another column stating which method from RGI is being used by those actions?
- [ ] https://github.com/bokulich-lab/q2-amr/issues/14
- [ ] https://github.com/bokulich-lab/q2-amr/issues/15
- [ ] https://github.com/bokulich-lab/q2-amr/issues/16
```
